sudo: false
language: c
os:
  - linux
#  - osx
compiler:
#  - clang
  - gcc
env:
  - MPICH_TESTS=init
  - MPICH_TESTS=info
  - MPICH_TESTS=attr
  - MPICH_TESTS=datatype
  - MPICH_TESTS=pt2pt
  - MPICH_TESTS=rma
  - MPICH_TESTS=threads
  - MPICH_TESTS=comm
  - MPICH_TESTS=group
  - MPICH_TESTS=coll
  - MPICH_TESTS=spawn
  - MPICH_TESTS=topo
  - MPICH_TESTS=io
  - MPICH_TESTS=impls
  - MPICH_TESTS=mpi_t
  - MPICH_TESTS=errhan
  - MPICH_TESTS=errors
  - MPICH_TESTS=perf
#addons:
#  apt:
#    sources:
#    - ubuntu-toolchain-r-test
#    packages:
#    - gcc-4.8
#    - g++-4.8
before_install:
  - export TRAVIS_ROOT=$HOME/travis
  - mkdir $TRAVIS_ROOT
  - export PATH=$TRAVIS_ROOT/bin:$PATH
  - sh .travis-install-autotools $TRAVIS_ROOT
  - which automake
  - automake --version
  - which autoconf
  - autoconf --version
  - ./autogen.sh
install:
  - ./configure --prefix=$TRAVIS_ROOT --disable-fortran --disable-cxx #--enable-strict
  - make -j2
  - make install
before_script:
  - make check
script:
  - cd test/mpi
  - echo '!util:all' > testlist
  - echo "${MPICH_TESTS}" >> testlist
  - cat testlist
  - ./runtests -tests=testlist \
               -np=2 -maxnp=3 \
               -verbose -showprogress \
               -mpiexec=${TRAVIS_ROOT}/bin/mpiexec
               #-xmlfile=summary.xml -tapfile=summary.tap -junitfile=summary.junit.xm
#runtests [-tests=testfile] [-np=nprocesses]
#        [-maxnp=max-nprocesses] [-srcdir=location-of-tests]
#        [-ppn=max-proc-per-node] [-ppnarg=string]
#        [-timelimitarg=string] [-mpiversion=major.minor]
#        [-xmlfile=filename ] [-tapfile=filename ]
#        [-junitfile=filename ] [-noxmlclose]
#        [-verbose] [-showprogress] [-debug] [-batch]
after_failure:
  - echo "Sad Panda"
notifications:
  email:
    recipients:
      - jeff.science@gmail.com
    on_success: [change]
    on_failure: [always]
